[plugin]
author = "ricewind"
description = "Additional elements for themes"
id = "steam-theme-essentials"
name = "Theme Essentials"
version = "1.0.0"

[assets]
resources = ["locales"]

[backend]
entry = "src/backend/main.lua"
sources = ["src/backend/**/*.lua"]

[frontend]
entry = "src/index.tsx"

[dev]
reload_steamui_when = "both"
